name: my_portfolio
description: A new my portfolio project.

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_fonts: ^2.2.0
  animated_text_kit: ^4.2.1
  url_launcher: ^6.0.18
  flutter_html: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Enables the `pub run build_runner` command
  build_runner: ^2.1.7
  # Includes the JavaScript compilers
  build_web_compilers: ^3.2.2
  # The Font Awesome Icon pack available as Flutter Icons.
  font_awesome: any

flutter:
  uses-material-design: true
